<?php

use App\Support\SiteSettings;
use Illuminate\Support\Facades\App;

if (! function_exists('site_setting')) {
    function site_setting(string $key, mixed $default = null): mixed
    {
        return SiteSettings::get($key, $default);
    }
}

if (!function_exists('t')) {
    function t(string $key): string
    {
        $translations = [
            'id' => [
                'indoor_performance'  => 'Pertunjukan Dalam',
                'outdoor_performance' => 'Pertunjukan Luar',
                'angklung_types'      => 'Jenis-Jenis Angklung',
                'sejarah_profile' => 'Sejarah & Profil',
                'heritage' => 'Warisan',
                'experience' => 'Pengalaman',
                'visit_us' => 'Kunjungi Kami',
                'stories' => 'Cerita',
                'corporate' => 'Korporat',
                'book_now' => 'Pesan Sekarang',
                'the_legend' => 'Legenda',
                'udjo_ngalagena' => 'Udjo Ngalagena',
                'history_of_sau' => 'Sejarah SAU',
                'angklung' => 'Angklung',
                'definition' => 'Definisi & Karakter',
                'angklung_history' => 'Sejarah Angklung',
                'how_to_make' => 'Cara Membuat',
                'instruments' => 'Instrumen',
                'angklung_unit' => 'Unit Angklung',
                'arumba_ensemble' => 'Ansambel Arumba',
                'attractions' => 'Atraksi',
                'art_performance' => 'Pertunjukan Seni',
                'academy' => 'Akademi',
                'venue_site' => 'Venue & Denah Lokasi',
                'banquet' => 'Jamuan',
                'craftsmanship' => 'Kerajinan',
                'bamboo_craft' => 'Produksi Bambu & Kerajinan',
                'souvenir_shop' => 'Toko Suvenir',
                'booking' => 'Pemesanan',
                'reservation_info' => 'Info Reservasi',
                'logistics' => 'Logistik',
                'getting_here' => 'Cara ke Sini',
                'hotels' => 'Hotel di Bandung',
                'visitor_tips' => 'Tips Pengunjung',
                'city_guide' => 'Panduan Kota',
                'attractions_near' => 'Atraksi Dekat SAU',
                'media_center' => 'Pusat Media',
                'news_events' => 'Berita & Acara',
                'promo_specials' => 'Promo & Spesial',
                'testimonials' => 'Testimoni',
                'creative' => 'Kreatif',
                'photo_gallery' => 'Galeri Foto',
                'video_gallery' => 'Galeri Video',
                'angklung_is_indonesia' => 'Angklung adalah Indonesia',
                'assets' => 'Aset',
                'ebrochure' => 'E-Brosur',
                'downloads_hub' => 'Hub Unduhan',
                'company_profile' => 'Profil Perusahaan',
                'about_sau' => 'Tentang SAU',
                'vision_mission' => 'Visi & Misi',
                'business_units' => 'Unit Bisnis',
                'achievements' => 'Pencapaian',
                'partnerships' => 'Kemitraan',
                'investors' => 'Pertumbuhan (Investor)',
                'marketing_hub' => 'Hub Pemasaran',
                'csr' => 'Aktivitas SAU (CSR)',
                'careers' => 'Karir',
                'career_center' => 'Pusat Karir',
                'executive_profile' => 'Profil Eksekutif',
                'sanctuary' => 'Tempat Suci',
                'connect' => 'Hubungi',
                'follow' => 'Ikuti',
                'tagline' => 'Alam, Budaya Dalam Harmoni',
                'description' => 'Melestarikan detak jantung harmoni Sunda untuk panggung global. Tempat suci Warisan Budaya Dunia UNESCO.',
                'address' => 'Jl. Padasuka 118, Bandung 40192',
                'rights' => 'SAUNG ANGKLUNG UDJO | WARISAN GLOBAL INDONESIA',
                'privacy' => 'Kebijakan Privasi',
                'terms' => 'Syarat Layanan',
                'unesco_badge' => 'Mahakarya Budaya Dunia UNESCO',
                'vision_mission' => 'Visi & Misi',
                'admin_wa' => 'Hubungi Kami',
                'title' => 'Pilih Admin',
                'admin_1_name' => 'Admin SAU 1',
                'admin_1_desc' => 'Info Reservasi',
                'admin_2_name' => 'Admin SAU 2',
                'admin_2_desc' => 'Pembelian Angklung',
                'souvenir_name' => 'Toko Souvenir',
                'souvenir_desc' => 'Pembelian Souvenir',

            ],
            'en' => [
                'indoor_performance'  => 'Indoor Performance',
                'outdoor_performance' => 'Outdoor Performance',
                'angklung_types'      => 'Types of Angklung',
                'sejarah_profile' => 'History & Profile',
                'heritage' => 'Heritage',
                'experience' => 'Experience',
                'visit_us' => 'Visit Us',
                'stories' => 'Stories',
                'corporate' => 'Corporate',
                'book_now' => 'Book Now',
                'the_legend' => 'The Legend',
                'udjo_ngalagena' => 'Udjo Ngalagena',
                'history_of_sau' => 'History of SAU',
                'angklung' => 'Angklung',
                'definition' => 'Definition & Character',
                'angklung_history' => 'Angklung History',
                'how_to_make' => 'How to Make',
                'instruments' => 'Instruments',
                'angklung_unit' => 'Angklung Unit',
                'arumba_ensemble' => 'Arumba Ensemble',
                'attractions' => 'Attractions',
                'art_performance' => 'Art Performance',
                'academy' => 'Academy',
                'venue_site' => 'Venue & Site Plan',
                'banquet' => 'Banquet',
                'craftsmanship' => 'Craftsmanship',
                'bamboo_craft' => 'Bamboo & Craft Production',
                'souvenir_shop' => 'Souvenir Shop',
                'booking' => 'Booking',
                'reservation_info' => 'Reservation Info',
                'logistics' => 'Logistics',
                'getting_here' => 'Getting Here',
                'hotels' => 'Hotels in Bandung',
                'visitor_tips' => 'Visitor Tips',
                'city_guide' => 'City Guide',
                'attractions_near' => 'Attractions Near SAU',
                'media_center' => 'Media Center',
                'news_events' => 'News & Events',
                'promo_specials' => 'Promo & Specials',
                'testimonials' => 'Testimonials',
                'creative' => 'Creative',
                'photo_gallery' => 'Photo Gallery',
                'video_gallery' => 'Video Gallery',
                'angklung_is_indonesia' => 'Angklung is Indonesia',
                'assets' => 'Assets',
                'ebrochure' => 'E-Brochure',
                'downloads_hub' => 'Downloads Hub',
                'company_profile' => 'Company Profile',
                'about_sau' => 'About SAU Company',
                'vision_mission' => 'Vision & Mission',
                'business_units' => 'Business Units',
                'achievements' => 'Achievements',
                'partnerships' => 'Partnerships',
                'investors' => 'Growth (Investors)',
                'marketing_hub' => 'Marketing Hub',
                'csr' => 'SAU Activities (CSR)',
                'careers' => 'Careers',
                'career_center' => 'Career Center',
                'executive_profile' => 'Executive Profile',
                'sanctuary' => 'Sanctuary',
                'connect' => 'Connect',
                'follow' => 'Follow',
                'tagline' => 'Nature, Culture In Harmony',
                'description' => 'Preserving the heartbeat of Sundanese harmony for the global stage. A UNESCO World Cultural Heritage sanctuary.',
                'address' => 'Jl. Padasuka 118, Bandung 40192',
                'rights' => 'SAUNG ANGKLUNG UDJO | INDONESIA GLOBAL HERITAGE',
                'privacy' => 'Privacy Policy',
                'terms' => 'Terms of Service',
                'unesco_badge' => 'UNESCO World Cultural Heritage',
                'vision_mission' => 'Vision & Mission',
                'admin_wa'  => 'Contact Us',
                'title' => 'Choose an Admin',
                'admin_1_name' => 'SAU Admin 1',
                'admin_1_desc' => 'Reservation Information',
                'admin_2_name' => 'SAU Admin 2',
                'admin_2_desc' => 'Angklung Purchase',
                'souvenir_name' => 'Souvenir Shop',
                'souvenir_desc' => 'Souvenir Purchase',
                ],
        ];

        $locale = App::getLocale() ?: 'id';

        return $translations[$locale][$key] ?? $key;
    }
}
